/**
 * FinCal - Retire Smart — Excel Export
 * Sheet 1: Summary / Inputs
 * Sheet 2: Year-by-Year Table (DTT model: AGE, Savings, SIP, Returns, Withdrawals, Status)
 * Sheet 3: What-If Comparison
 */
import * as XLSX from "xlsx";
import { generateDTTSimulation, formatINRFull, sipRequired } from "./formulas";
import { DEFAULTS } from "./constants";

export function exportRetirementPlan(data) {
  const {
    currentAge, retirementAge, lifeExpectancy,
    monthlyExpense, monthlySip, annualReturn,
    inflationRate, postRetirementReturn,
    existingSavings, lifestyle,
    results,
  } = data;

  const stepUpRate     = DEFAULTS.STEP_UP_RATE;
  const capitalGainTax = DEFAULTS.CAPITAL_GAIN_TAX;
  const yearsToRetire  = retirementAge - currentAge;

  // Run DTT simulation
  const { rows, postRetirementMonthly } = generateDTTSimulation({
    currentAge,
    retirementAge,
    planningAge:       lifeExpectancy,
    currentSavings:    existingSavings,
    monthlySIP:        monthlySip,
    stepUpRatePct:     stepUpRate,
    annualGrowthPct:   annualReturn,
    capitalGainTaxPct: capitalGainTax,
    monthlyExpenses:   monthlyExpense,
    inflationRatePct:  inflationRate,
  });

  const wb = XLSX.utils.book_new();

  // ── SHEET 1: INPUTS & SUMMARY ──────────────────────────────────────────
  const summary = [
    ["RETIREMENT CALCULATOR", "", "", ""],
    ["Generated by FinCal - Retire Smart", "", "", ""],
    [],
    ["ENTER YOUR INPUTS", "", "", ""],
    [],
    ["MONTHLY INCOME",           "", "", ""],
    ["Current Monthly Expenses", formatINRFull(monthlyExpense), "", ""],
    [],
    ["YOUR AGE",                 currentAge + " years", "", "CURRENT SAVINGS", formatINRFull(existingSavings)],
    ["Retirement Age",           retirementAge + " years", "", "Monthly SIP",   formatINRFull(monthlySip)],
    ["Planning Till Age",        lifeExpectancy + " years", "", "Step Up SIP",  stepUpRate + "% per year"],
    [],
    ["Growth (Annual Return)",   annualReturn + "%", "", "POST RETIREMENT MONTHLY EXPENSES", formatINRFull(postRetirementMonthly)],
    ["Capital Gain Tax",         capitalGainTax + "%", "", "INFLATION RATE", inflationRate + "%"],
    ["Lifestyle",                lifestyle || "normal", "", "", ""],
    [],
    ["RESULTS", "", "", ""],
    ["Inflation-Adjusted Monthly Expense at Retirement", formatINRFull(postRetirementMonthly)],
    ["Total Corpus Required",                            formatINRFull(results?.corpus || 0)],
    ["Monthly SIP Required to Hit Goal",                 formatINRFull(results?.requiredSip || 0)],
    ["Your Monthly SIP",                                 formatINRFull(monthlySip)],
    ["Projected Corpus from your SIP",                   formatINRFull(results?.sipCorpus || 0)],
    ["Total Amount Invested",                            formatINRFull(results?.totalInvested || 0)],
    ["Total Estimated Gains",                            formatINRFull(results?.totalGain || 0)],
    ["Plan Coverage",                                    (results?.goalProgress || 0) + "%"],
  ];

  const s1 = XLSX.utils.aoa_to_sheet(summary);
  s1["!cols"] = [{wch:44},{wch:24},{wch:4},{wch:36},{wch:24}];
  XLSX.utils.book_append_sheet(wb, s1, "Summary");

  // ── SHEET 2: YEAR-BY-YEAR (DTT MODEL) ─────────────────────────────────
  const tableHeader = [
    ["RESULTS"],
    [],
    ["AGE", "Starting Savings (₹)", "Additional Savings / SIP (₹)", "Return on Invested Amount (₹)", "Withdrawals (₹)", "Status"],
  ];

  const tableRows = rows.map(r => [
    r.age,
    r.savings < 0 ? 0 : r.savings,
    r.additionalSavings,
    r.returns,
    r.withdrawals,
    r.status || "",
  ]);

  // Add totals row
  const totalInvested   = rows.filter(r => r.age <= retirementAge).reduce((s, r) => s + r.additionalSavings, 0);
  const totalWithdrawn  = rows.filter(r => r.age > retirementAge).reduce((s, r) => s + r.withdrawals, 0);
  tableRows.push([]);
  tableRows.push(["TOTAL", "", formatINRFull(totalInvested), "", formatINRFull(totalWithdrawn), ""]);

  const s2 = XLSX.utils.aoa_to_sheet([...tableHeader, ...tableRows]);
  s2["!cols"] = [{wch:8},{wch:24},{wch:34},{wch:34},{wch:22},{wch:24}];
  XLSX.utils.book_append_sheet(wb, s2, "Year by Year");

  // ── SHEET 3: WHAT-IF COMPARISON ───────────────────────────────────────
  const startAges = [currentAge, currentAge+5, currentAge+10, currentAge+15]
    .filter(a => a < retirementAge - 4);

  const wi = [
    ["WHAT-IF: Impact of Starting Age on Monthly SIP Required"],
    ["Target Corpus:", formatINRFull(results?.corpus || 0), "Annual Return:", annualReturn+"%"],
    [],
    ["Start Age", "Years to Retire", "Monthly SIP Needed (₹)", "Total You Invest (₹)", "Extra vs Starting Now (₹)", "% Extra"],
    ...startAges.map((age, i) => {
      const yrs  = retirementAge - age;
      const sip  = Math.round(sipRequired(results?.corpus || 0, existingSavings, annualReturn, yrs));
      const inv  = sip * yrs * 12;
      const base = Math.round(sipRequired(results?.corpus || 0, existingSavings, annualReturn, retirementAge - currentAge));
      return [
        age, yrs, sip, inv,
        i === 0 ? 0 : sip - base,
        i === 0 ? "Baseline" : `+${(((sip-base)/base)*100).toFixed(1)}%`,
      ];
    }),
    [],
    ["KEY INSIGHT: Delaying 10 years can more than double your required monthly SIP."],
  ];

  const s3 = XLSX.utils.aoa_to_sheet(wi);
  s3["!cols"] = [{wch:12},{wch:18},{wch:26},{wch:26},{wch:28},{wch:14}];
  XLSX.utils.book_append_sheet(wb, s3, "What-If Comparison");

  XLSX.writeFile(wb, "FinCal - Retire Smart_Retirement_Plan.xlsx");
}
